import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store } from '../main/storage';
import { readProfile, saveProfile, archiveHistory, restoreHistory, profileSummary } from '../main/local-profile';
function fixture(t:any){const root=mkdtempSync(join(tmpdir(),'akorith-profile-'));let store=new Store(join(root,'db.sqlite'));t.after(()=>{store.close();rmSync(root,{recursive:true,force:true})});return {get store(){return store},reopen(){store.close();store=new Store(join(root,'db.sqlite'));return store}}}
test('local identity validates input and persists independently of model settings',t=>{const f=fixture(t),settings=f.store.settings();saveProfile(f.store,{name:'  İbrahim  ',bio:' My work ',color:'blue'});assert.deepEqual(readProfile(f.reopen()),{name:'İbrahim',bio:'My work',color:'blue'});assert.deepEqual(f.store.settings(),settings);for(const value of [null,{name:'',bio:'',color:'slate'},{name:'x',bio:8,color:'blue'},{name:'x',bio:'',color:'red'}])assert.throws(()=>saveProfile(f.store,value));assert.equal(readProfile(f.store).name,'İbrahim')});
test('history clear and restart restore preserve preexisting archives, messages and native sessions',t=>{const f=fixture(t);const p=f.store.addProject('/fixture','Fixture'),a=f.store.createTask({projectId:p.id,providerId:'codex',model:'m'}),b=f.store.createTask({providerId:'ollama',model:'local'});f.store.updateTask(a.id,{nativeSessions:{codex:'session'},draft:'keep draft',pinned:true});f.store.updateTask(b.id,{archived:true});f.store.saveMessage({id:'m',taskId:a.id,turnId:'t',role:'assistant',content:'Keep me',activities:[],status:'completed',createdAt:1});assert.deepEqual(archiveHistory(f.store),{tasks:1,projects:1});assert.equal(f.store.project(p.id)?.hiddenFromSidebar,true);assert.equal(f.store.messages(a.id)[0].content,'Keep me');assert.equal(profileSummary(f.reopen()).canRestoreHistory,true);assert.deepEqual(restoreHistory(f.store),{tasks:1,projects:1});assert.equal(f.store.task(a.id).archived,false);assert.equal(f.store.task(a.id).draft,'keep draft');assert.equal(f.store.task(a.id).nativeSessions.codex,'session');assert.equal(f.store.task(b.id).archived,true);assert.equal(f.store.project(p.id)?.hiddenFromSidebar,false);assert.deepEqual(restoreHistory(f.store),{tasks:0,projects:0})});
test('active tasks block clear atomically; reopening a hidden project reveals it',t=>{const f=fixture(t),p=f.store.addProject('/fixture','Fixture'),a=f.store.createTask({projectId:p.id,providerId:'codex',model:'m'});f.store.updateTask(a.id,{status:'waiting'});assert.throws(()=>archiveHistory(f.store),/active tasks/);assert.equal(f.store.task(a.id).archived,false);assert.equal(f.store.project(p.id)?.hiddenFromSidebar,undefined);f.store.updateTask(a.id,{status:'completed'});archiveHistory(f.store);assert.equal(f.store.addProject('/fixture','Ignored').id,p.id);assert.equal(f.store.project(p.id)?.hiddenFromSidebar,false)});
test('usage counts assistant reports once and preserves unknown costs',t=>{const f=fixture(t),a=f.store.createTask({providerId:'codex',model:'m'});const add=(id:string,role:'user'|'assistant',usage:any)=>f.store.saveMessage({id,taskId:a.id,turnId:id,role,content:'',activities:[],status:'completed',createdAt:1,usage});add('a','assistant',{totalTokens:10,inputTokens:6,outputTokens:4,costUsd:0});add('b','assistant',{inputTokens:2,outputTokens:3});add('c','user',{totalTokens:999,costUsd:99});add('d','assistant',{inputTokens:4});const s=profileSummary(f.store);assert.equal(s.reportedTokens,15);assert.equal(s.usageReports,2);assert.equal(s.costReports,1);assert.equal(s.reportedCostUsd,0)});
